### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by darekmer** [joomdev/Astroid-Template-One#1]
Backend : Warning: file_get_contents(E:\xampp\htdocs\xxx/templates/astroid_template_one/params/14.json): failed to open stream: No such file or directory in E:\xampp\htdocs\xxx\libraries\astroid\framework\template.php on line 157
Front : Please install and activate Astroid Framework in order to use this template.

**Comment by hiteshaggarwal** [comment]
Hi @darekmer , Thanks for excitement, It's an Astroid Framework Based template. If you do not have any idea of [Astroid Framework](https://github.com/joomdev/Astroid-Framework) then please check [link](https://astroidframework.com/). Also, Please wait for proper release of template, We just added this repository and planning to release template shortly. Thanks

**Comment by darekmer** [comment]
;)
Hi, I even translate Astroid Framework into Polish,
new one appeared, I wanted to check how it works

**Comment by hiteshaggarwal** [comment]
@chetanmadaan , Can you help @darekmer regarding translations. @darekmer [this](https://docs.joomdev.com/category/astroid-user-manual/) is the user manual for Astroid. See, If it can helpful for you. Thanks

**Comment by chetanmadaan** [comment]
Sure @hiteshaggarwal, thanks for jumping on this quickly.

@darekmer Thanks for the translation. We just got the notification a few hours ago regarding the completion of polish translation for Astroid, JD  Simple contact form and majority of JD builder files as well.
We'll be putting it all together as an installable language package and release in the coming week.

Thanks again for all the hard work.
Like Hitesh said above, Astroid_template_one is a new template for astroid that'll go with Astroid framework in the coming weeks and you'll be able to use it on your existing sites and new sites and this will be compatible for both Joomla 3 and Joomla 4!

Stay put!
